name: CI / Tests

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    merge_group: # Add this to ensure checks run for the merge queue
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build packages
              run: |
                  pnpm build
                  sleep 60

            - name: Run tests
              run: |
                  pnpm test
                  sleep 120

            - name: Verify Changesets (Optional but recommended)
              # This step ensures that a .changeset file is present for new features/fixes
              # and would fail the PR if it's missing when needed.
              # It does NOT apply the version bump.
              if: github.event_name == 'pull_request'
              run: pnpm changeset status --since=main
